#!/usr/bin/env bash
set -e

# Capture and discard stdin, to avoid pandoc waiting on user input
[ -t 0 ] || cat > /dev/null

OUT_OPTIONS=(-f json -t html -s --mathml --template "$TEMPLATE_PATH")

# Provide 'path' arg for our View Source links.
OUT_OPTIONS+=(-M "path=${SOURCE_PATH:-$SOURCE}")

# If filename contains a date (e.g. blogs), provide it to the output template
if D=$(echo "$SOURCE" | grep -om1 -P "\\d{4}-\\d{2}-\\d{2}")
then
    OUT_OPTIONS+=(-M "date=$D")
fi

# We don't use pandoc's --filter option, as it buffers stderr which makes
# debugging harder. 'postprocessor' comes from the file's YAML (default: 'cat')
pandoc -t json "$SOURCE"       |
    pandoc "${OUT_OPTIONS[@]}" |
    "${postprocessor:-cat}"    > "$DEST" || echo "Rendering pipeline echoed"

# Check output

[[ -e "$DEST" ]]                      || echo "Error: '$DEST' wasn't created"
grep '[^ \n\t]' < "$DEST" > /dev/null || echo "Error: Output is empty"
